### PR TITLE
Add margin feature

### PR DESCRIPTION
**Pull request by pierrzacharias**
Hi !
I added margin on your work between windows and at screen edges. 
There is also a config window to select the size of the gaps.

### CODE REVIEW

**Comment by lucmos** [comment]
@pierrzacharias thank you for the PR! Currently, I'm a bit busy with other stuff, I'll merge it in a few weeks :)

**Comment by EnriqueWood** [comment]
@pierrzacharias It'd be very nice to have this feature merged, please don't forget it

**Comment by pierrzacharias** [comment]
HIi, this is up to @pierrzacharias  to merge. You can get the version with additionnal margin from my fork.

**Comment by lucmos** [comment]
Hello @pierrzacharias, thanks again for the PR.

I am trying to test the margin feature. I am sorry but it is not completely clear to me how it works. 
Can you briefly describe it? e.g. how do you open the config window?

**Comment by EnriqueWood** [comment]
> Hello @pierrzacharias, thanks again for the PR.
> 
> I am trying to test the margin feature. I am sorry but it is not completely clear to me how it works.
> Can you briefly describe it? e.g. how do you open the config window?

@pierrzacharias could you, please?

**Comment by mitnworb** [comment]
> HIi, this is up to @lucmos to merge. You can get the version with additionnal margin from my fork.

@pierrzacharias Thank you for adding gaps, but I am having an issue with your fork.  I really only use 3 shortcut and one of them is not working.  It's "Move Window to center-height (4x2 center biased)". Left and Right-height work fine.  It works fine from lucmos' repo.  I even merged your commits into my own fork or lucmos' repo and no go.  Any ideas?  Thanks again.

**Pull request closed without merging**
