### PR TITLE
Update to work with Wayland and KDE 6 tools

### PR DESCRIPTION
**Pull request by cyberang3l**
Updates to make the script work under KDE 6 and wayland (the default for KDE 6).

Moreover, the (un)installation scripts have been improved significantly to provide
a much better user experience where all the changes are reflected immediately
without the need to restart x11/wayland with the `kwin_x11/kwin_wayland --replace`
commands.

Also removed the "sed" command from the uninstall script, as this is not needed
any more. The changes are reflected by using standard commands/tooling
provided by kde.

Sample:
```
$ scripts/install.sh
Already uninstalled
updating: contents/ (stored 0%)
updating: contents/code/ (stored 0%)
updating: contents/code/main.js (deflated 86%)
updating: LICENSE (deflated 62%)
updating: metadata.json (deflated 47%)
updating: contents/code/.main.js.swp (deflated 91%)
Packaged in /home/user/Source/UltrawideWindows/ultrawidewindows.kwinscript
Successfully installed /home/user/.local/share/kwin/scripts/ultrawidewindows/

# Try to use the registered shortcuts now. Should be working.
# Also notice that the expected config files and dbus state have been updated

$ cat ~/.config/kwinrc | grep ultra
ultrawidewindowsEnabled=true

$ qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.shortcutNames | grep MoveWindow
MoveWindowToFitDownLeft23_center_biased
MoveWindowToRightHeight3x2
MoveWindowToMaximize4
MoveWindowToUpLeft2x2
MoveWindowToMaximize
MoveWindowToDownLeft3x2
MoveWindowToUpRight23
MoveWindowToRightHeight4x2_centerbiased
MoveWindowToUpCenter2x2
MoveWindowToUpRight2x2
MoveWindowToCenterRightHeight4x2_centerbiased
MoveWindowToLeftHeight4x2_centerbiased
MoveWindowToFitDownRight23_center_biased
MoveWindowToUpRight3x2
MoveWindowToCenterLeftHeight4x2_centerbiased
MoveWindowToUpRight4x2_centerbiased
MoveWindowToDownCenter3x2
MoveWindowToMaximize3
MoveWindowToDownCenter4x2_centerbiased
MoveWindowToUpLeft23_center_biased
MoveWindowToDownCenter2x2
MoveWindowToLeftHeight3x2
MoveWindowToCenterHeight4x2_centerbiased
MoveWindowToUpCenter3x2
MoveWindowToUpCenter23_center_biased
MoveWindowToDownCenter23_center_biased
MoveWindowToLeftHeight23_center_biased
MoveWindowToDownLeft2x2
MoveWindowToUpLeft23
MoveWindowToFitDownLeft23
MoveWindowToLeftHeight2x2
MoveWindowToMaximize1
MoveWindowToMaximize2
MoveWindowToDownRight4x2_centerbiased
MoveWindowToFitDownRight23
MoveWindowToUpRight23_center_biased
MoveWindowToUpCenter4x2_centerbiased
MoveWindowToUpLeft4x2_centerbiased
MoveWindowToCenter
MoveWindowToCenter1
MoveWindowToDownRight3x2
MoveWindowToUpLeft3x2
MoveWindowToUpCenter23
MoveWindowToDownRight2x2
MoveWindowToCenterHeight3x2
MoveWindowToRightHeight23_center_biased
MoveWindowToDownCenter23
MoveWindowToCenterHeight23_center_biased
MoveWindowToLeftHeight23
MoveWindowToDownLeft4x2_centerbiased
MoveWindowToRightHeight23
MoveWindowToRightHeight2x2

$ cat kglobalshortcutsrc  | grep Ultra
MoveWindowToCenter=Ctrl+Num+5,none,UltrawideWindows: Center Window
MoveWindowToCenter1=Alt+Num+5,none,UltrawideWindows: Center Window (copy)
MoveWindowToCenterHeight23_center_biased=Meta+Alt+Num+5,none,UltrawideWindows: Move Window to fit center-height 2/3 width (center biased)
MoveWindowToCenterHeight3x2=Meta+Num+5,none,UltrawideWindows: Move Window to center-height (3x2)
MoveWindowToCenterHeight4x2_centerbiased=Meta+Ctrl+Num+5,none,UltrawideWindows: Move Window to center-height (4x2 center biased)
MoveWindowToCenterLeftHeight4x2_centerbiased=Meta+Ctrl+Shift+Num+4,none,UltrawideWindows: Move Window to center-left-height (4x2 center biased)
MoveWindowToCenterRightHeight4x2_centerbiased=Meta+Ctrl+Shift+Num+6,none,UltrawideWindows: Move Window to center-right-height (4x2 center biased)
MoveWindowToDownCenter23=Alt+Num+2,none,UltrawideWindows: Move Window to down-width 2/3
MoveWindowToDownCenter23_center_biased=Meta+Alt+Num+2,none,UltrawideWindows: Move Window to down-center 2/3 (center biased)
MoveWindowToDownCenter2x2=Ctrl+Num+2,none,UltrawideWindows: Move Window to down-width (2x2)
MoveWindowToDownCenter3x2=Meta+Num+2,none,UltrawideWindows: Move Window to down-center (3x2)
MoveWindowToDownCenter4x2_centerbiased=Meta+Ctrl+Num+2,none,UltrawideWindows: Move Window to down-center (4x2 center biased)
MoveWindowToDownLeft2x2=Ctrl+Num+1,none,UltrawideWindows: Move Window to down-left (2x2)
MoveWindowToDownLeft3x2=Meta+Num+1,none,UltrawideWindows: Move Window to down-left (3x2)
MoveWindowToDownLeft4x2_centerbiased=Meta+Ctrl+Num+1,none,UltrawideWindows: Move Window to down-left (4x2 center biased)
MoveWindowToDownRight2x2=Ctrl+Num+3,none,UltrawideWindows: Move Window to down-right (2x2)
MoveWindowToDownRight3x2=Meta+Num+3,none,UltrawideWindows: Move Window to down-right (3x2)
MoveWindowToDownRight4x2_centerbiased=Meta+Ctrl+Num+3,none,UltrawideWindows: Move Window to down-right (4x2 center biased)
MoveWindowToFitDownLeft23=Alt+Num+1,none,UltrawideWindows: Move Window to fit down-left 2/3 width\s
MoveWindowToFitDownLeft23_center_biased=Meta+Alt+Num+1,none,UltrawideWindows: Move Window to fit down-left 2/3 width (center biased)
MoveWindowToFitDownRight23=Alt+Num+3,none,UltrawideWindows: Move Window to fit down-right 2/3 width\s
MoveWindowToFitDownRight23_center_biased=Meta+Alt+Num+3,none,UltrawideWindows: Move Window to fit down-right 2/3 width (center biased)
MoveWindowToLeftHeight23=Alt+Num+4,none,UltrawideWindows: Move Window to fit left-height 2/3 width\s
MoveWindowToLeftHeight23_center_biased=Meta+Alt+Num+4,none,UltrawideWindows: Move Window to fit left-height 2/3 width (center biased)
MoveWindowToLeftHeight2x2=Ctrl+Num+4,none,UltrawideWindows: Move Window to left-height (2x2)
MoveWindowToLeftHeight3x2=Meta+Num+4,none,UltrawideWindows: Move Window to left-height (3x2)
MoveWindowToLeftHeight4x2_centerbiased=Meta+Ctrl+Num+4,none,UltrawideWindows: Move Window to left-height (4x2 center biased)
MoveWindowToMaximize=Meta+Num+0,none,UltrawideWindows: Maximize Window
MoveWindowToMaximize1=Alt+Num+0,none,UltrawideWindows: Maximize Window (copy)
MoveWindowToMaximize2=Ctrl+Num+0,none,UltrawideWindows: Maximize Window (copy2)
MoveWindowToMaximize3=Meta+Ctrl+Num+0,none,UltrawideWindows: Maximize Window (copy2)
MoveWindowToMaximize4=Meta+Alt+Num+0,none,UltrawideWindows: Maximize Window (copy2)
MoveWindowToRightHeight23=Alt+Num+6,none,UltrawideWindows: Move Window to fit right-height 2/3 width\s
MoveWindowToRightHeight23_center_biased=Meta+Alt+Num+6,none,UltrawideWindows: Move Window to fit right-height 2/3 width (center biased)
MoveWindowToRightHeight2x2=Ctrl+Num+6,none,UltrawideWindows: Move Window to right-height (2x2)
MoveWindowToRightHeight3x2=Meta+Num+6,none,UltrawideWindows: Move Window to right-height (3x2)
MoveWindowToRightHeight4x2_centerbiased=Meta+Ctrl+Num+6,none,UltrawideWindows: Move Window to right-height (4x2 center biased)
MoveWindowToUpCenter23=Alt+Num+8,none,UltrawideWindows: Move Window to up-width 2/3
MoveWindowToUpCenter23_center_biased=Meta+Alt+Num+8,none,UltrawideWindows: Move Window to up-center 2/3 (center biased)
MoveWindowToUpCenter2x2=Ctrl+Num+8,none,UltrawideWindows: Move Window to up-width (2x2)
MoveWindowToUpCenter3x2=Meta+Num+8,none,UltrawideWindows: Move Window to up-center (3x2)
MoveWindowToUpCenter4x2_centerbiased=Meta+Ctrl+Num+8,none,UltrawideWindows: Move Window to up-center (4x2 center biased)
MoveWindowToUpLeft23=Alt+Num+7,none,UltrawideWindows: Move Window to fit up-left 2/3 width\s
MoveWindowToUpLeft23_center_biased=Meta+Alt+Num+7,none,UltrawideWindows: Move Window to fit up-left 2/3 width (center biased)
MoveWindowToUpLeft2x2=Ctrl+Num+7,none,UltrawideWindows: Move Window to up-left (2x2)
MoveWindowToUpLeft3x2=Meta+Num+7,none,UltrawideWindows: Move Window to up-left (3x2)
MoveWindowToUpLeft4x2_centerbiased=Meta+Ctrl+Num+7,none,UltrawideWindows: Move Window to up-left (4x2 center biased)
MoveWindowToUpRight23=Alt+Num+9,none,UltrawideWindows: Move Window to fit up-right 2/3 width\s
MoveWindowToUpRight23_center_biased=Meta+Alt+Num+9,none,UltrawideWindows: Move Window to fit up-right 2/3 width (center biased)
MoveWindowToUpRight2x2=Ctrl+Num+9,none,UltrawideWindows: Move Window to up-right (2x2)
MoveWindowToUpRight3x2=Meta+Num+9,none,UltrawideWindows: Move Window to up-right (3x2)
MoveWindowToUpRight4x2_centerbiased=Meta+Ctrl+Num+9,none,UltrawideWindows: Move Window to up-right (4x2 center biased)

$ scripts/uninstall.sh
Unloading ultrawidewindows
Successfully uninstalled /home/user/.local/share/kwin/scripts/ultrawidewindows/

# Try to use the registered shortcuts now. They shouldn't be working anymore

# Notice also the following config files and corresponding dbus state have been
# cleaned up (following commands return nothing)
$ cat ~/.config/kwinrc | grep ultra
$ $ qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.shortcutNames | grep MoveWindow
$ cat kglobalshortcutsrc  | grep Ultra
```

### CODE REVIEW

**Comment by eliaskaerle** [comment]
Amazing!!!

**Comment by eliaskaerle** [comment]
I did, yes! But the mentioned folder was not deleted.
However, I think I broke something before your PR while trying to repair it, so it's probably not a problem with your script.

**Comment by lucmos** [comment]
Thanks for the PR!

How does this PR compare with #42 from @destogl? 

Sorry for the slow turnaround time, but these weeks are and will be very busy on my end

**Comment by cyberang3l** [comment]
#42 looks like it technically resolves the same issue.

The only difference I can spot is that #42 is using `kwriteconfig6` to enable ultrawidewindows:
```
kwriteconfig6 --file kwinrc --group Plugins --key ultrawidewindowsEnabled true # or use KWin Script configuration in System Settings
```

But this is not required with the `"EnabledByDefault": true` option in the json configuration (I haven't checked yet if with the kwriteconfig6 we don't have to run the `kwin_[wayland|x11] --replace` though, cause I see this part is removed in #42).

It's also removing the `UltrawideWindows: Center Window (copy)` shortcut, and doesn't make any other changes.

**Comment by cyberang3l** [comment]
Now there are more differences - spent some more time to figure out how we can apply the changes without restarting x11/wayland, and the results are very good! Have a look at the description that I just added in this PR.

**Comment by Fellhahn** [comment]
Many thanks to those involved for this PR, really saved my day

**Comment by DougEubanks** [comment]
@cyberang3l I appreciate you picking this up, with my Samsung Ultrawide monitor, this KWin script has become part of my usual workflow.

This isn't working on Fedora 40 dev for some reason.  Installing it through the GUI or using "kpackagetool6 --type=KWin/Script -i" says it installs successfully, but never shows up in the KWin settings panel and the shortcuts are never available.  I tried installing it at the user and global level and rebooting as well.

**Comment by destogl** [comment]
@cyberang3l thanks for this!! This is perfect and much better than my #42 PR.

@lucmos, we should proceed with this PR first, and then I can rebase my #42 to see if other changes are also interesting to be merged separately. What do you think?

**Comment by cyberang3l** [comment]
@DougEubanks sorry, I don't know what could be wrong with Fedora if KDE 6 is properly installed.

Did you try the install/uninstall scripts?

I've only tried this on KDE Neon, but I'm using standard KDE tooling in the install/uninstall scripts, so technically, the installation should be distro-agnostic.

**Comment by DougEubanks** [comment]
@cyberang3l

Thanks for your reply and again thank you for your work picking this up.

I was able to resolve this issue by installing the extra package kf5-plasma in Fedora, which includes the plasmapkg2 command.  Once I installed that package, the install script worked successfully.

I'm trying to include as much information in the fix as possible for other Fedora users to find.

**Review by lucmos — APPROVED** [review]

**Comment by lucmos** [comment]
Thanks again for the PR and to everyone for testing!

Going to merge and release on the store :rocket: :

**Pull request merged**
